// This file is automatically generated by Firebase Studio. Do not edit manually.

// To change which Firebase project this app is connected to, go to the
// Firebase console for this project and select "Project settings".

/**
 * The Firebase configuration object. This is a public-facing configuration
 * and is safe to include in your client-side code.
 *
 * Note: If you have not yet configured Firebase for this project, this object
 * will be empty.
 */
export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
};
